version: "3.8"
services:
  user_service:
    build: ./services/user_service
    ports:
      - "8001:8000"
      - "50051:50051"
  product_service:
    build: ./services/product_service
    ports:
      - "8002:8000"
      - "50052:50052"
